version: '3'
networks:
    laravel:
services:
    app:
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
        depends_on:
            - php
#            - redis
            - mysql
        networks:
               - laravel
        logging:
            options:
                max-size: 10m
                max-file: "5"

    mysql:
        image: mariadb:10.6
        restart: unless-stopped
        tty: true
        ports:
            - "3360:3306"
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel
        logging:
            options:
                max-size: 10m
                max-file: "5"

    php:
        user: 'www-data:www-data'
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
        networks:
            - laravel
        logging:
            options:
                max-size: 10m
                max-file: "5"

#    redis:
#        image: redis:alpine
#        restart: unless-stopped
#        ports:
#            - "6399:6379"
#        networks:
#            - laravel
#        logging:
#            options:
#                max-size: 10m
#                max-file: "5"
